// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xbdsbucdsbkkgxpwjcvb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhiZHNidWNkc2Jra2d4cHdqY3ZiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyODE5OTYsImV4cCI6MjA2Mzg1Nzk5Nn0.b1th76tNbA04K15Q4_BGgNdevDbAW5Dq5R-6l_nakwU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);